services:
  - type: cron
    name: receipt-ocr
    schedule: "*/10 * * * *"
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
    buildCommand: ""
    startCommand: |
      apt-get update &&
      apt-get install -y tesseract-ocr \
        tesseract-ocr-tha \
        tesseract-ocr-mya \
        tesseract-ocr-ukr \
        tesseract-ocr-ben &&
      pip install -r requirements.txt &&
      python receipt_automation.py
